# Welcome to Jekyll!

# Website settings
title: António Ferreira
description: António Ferreira's portfolio
keywords: Materials Science and Engineering, Georgia Tech, Northwestern University
#baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://antonioferreira.life  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author: # change following line to your infomation.
  name: António Ferreira  # Be used at blog posts' austhor.
  first_name: António  # Be used at index page about me section.
  last_name: Ferreira  # Be used at index page about me section.
  avatar: /static/assets/img/headshot.jpg  # upload your avatar at directory and edit it.
  github_username:  # Leave blank if you don't have now
  linkedin_id: antonio-ferreira2003 # Leave blank if you don't have now
  orcid_id: 0009-0008-1370-3772 # Leave blank if you don't have now
  facebook_username:  # Leave blank if you don't have now
  twitter_username:   # Leave blank if you don't have now
  email: antoniof@u.northwestern.edu  # Leave blank if you don't have now
  cv: http://antonioferreira.life/Antonio_Ferreira_Resume.pdf  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name:
    - name:
  skill_icon2:
    - name:
    - name:
  desc: "Currently pursuing a Ph.D. in Materials Science and Engineering at Northwestern University. I completed my M.S. in Materials Science and Engineering at Georgia Tech in May 2026, researching additive manufacturing of shape memory alloys (SMAs).<br><br>My studies are guided by a vision for the field: a future where new materials are developed at speed, from chemistry and property prediction using physics-based models, all the way through to large-scale manufacturing. I'm particularly interested in alloys for extreme environments and the advanced manufacturing techniques that enable them.<br><br>Alongside my studies, I work part-time at Havelar, a startup developing concrete 3D construction printing (3DCP) technology, where I contribute to hands-on engineering and business development. For fun, I practice Muay Thai, work out with friends, travel, and read."
# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name:

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id:

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

